export const WORKFLOW_ICON_NODE_SIZE = 56
export const WORKFLOW_ICON_NODE_WIDTH = WORKFLOW_ICON_NODE_SIZE
export const WORKFLOW_ICON_NODE_HEIGHT = WORKFLOW_ICON_NODE_SIZE
export const WORKFLOW_RESULT_NODE_WIDTH = 240
export const WORKFLOW_RESULT_NODE_HEIGHT = 135
export const WORKFLOW_ICON_NODE_FLOW_GAP_X = 228
export const WORKFLOW_ICON_NODE_FLOW_GAP_Y = 48
export const WORKFLOW_ICON_NODE_COLUMN_STRIDE = 136
export const WORKFLOW_ICON_NODE_ROW_STRIDE = 112

// Workflow ports belong visually to the compact icon, not to the generous connection gutter.
export const WORKFLOW_ICON_NODE_HANDLE_OFFSET = 8
export const WORKFLOW_EDGE_ROUTE_OFFSET = 8
export const WORKFLOW_EDGE_RAIL_GUTTER = 72
